# synthetic_processor.py
async def process_payment(charge_id: str, amount: float, failure_rate: float = FAILURE_RATE) -> ProcessorResponse: ...

# models.py
class ChargeRequest(BaseModel): ...
class ChargeResponse(BaseModel): ...
class AttemptSummary(BaseModel): ...
class ChargeStatusResponse(BaseModel): ...
class StatsResponse(BaseModel): ...