def get_db_path() -> str: ...
def init_db(db_path: str) -> None: ...
def get_connection(db_path: str) -> sqlite3.Connection: ...
def insert_charge(conn, charge_id, amount, currency, customer_id, description, max_retries) -> None: ...
def get_charge(conn, charge_id: str) -> dict | None: ...
def update_charge_status(conn, charge_id: str, status: str, retry_count: int = None, next_retry_at: str = None) -> None: ...
def insert_attempt(conn, charge_id, attempt_number, status, error_code, error_message, processor_response, duration_ms) -> None: ...
def get_attempts(conn, charge_id: str) -> list[dict]: ...
def get_stats(conn) -> dict: ...