class RetryOrchestrator:
    def __init__(self, db_path: str, failure_rate: float = FAILURE_RATE): ...
    async def start(self) -> None: ...
    async def stop(self, timeout: float = 10.0) -> None: ...
    async def enqueue(self, charge_id: str, delay_seconds: float = 0) -> None: ...
    @staticmethod
    def compute_backoff_delays(max_retries: int) -> list[int]: ...
    async def _process_queue(self) -> None: ...
    async def _attempt_charge(self, charge_id: str) -> None: ...
    def queue_depth(self) -> int: ...